version: '3'

services:
  postgres:
    image: postgres:16
    env_file: ./db.env
    environment:
      - POSTGRES_DB=codereview
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  codereview:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - default

volumes:
  pg_data:

networks:
    default:
        driver: bridge