definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  handler.User:
    properties:
      email:
        example: johndoe@gmail.com
        type: string
      password:
        example: "12345678"
        type: string
      username:
        example: johndoe
        type: string
    type: object
  model.User:
    description: User is the model representing a user in the system.
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        example: johndoe@gmail.com
        type: string
      id:
        type: string
      password:
        example: "12345678"
        type: string
      updatedAt:
        type: string
      username:
        example: johndoe
        type: string
    type: object
info:
  contact: {}
paths:
  /user/:
    get:
      consumes:
      - application/json
      description: get details of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create a new user with the provided information
      parameters:
      - description: User to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      summary: Create a new user
      tags:
      - users
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: User deleted
      summary: Delete a user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: get details of user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Get single user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: update user's information by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User information to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Update an existing user
      tags:
      - users
swagger: "2.0"
